# Standalone MSSQL Database for testing, docker-compose -f docker-compose.db_logistics.yml up -d

version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vda-db-logistics
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Strong_password123!}
      MSSQL_PID: ${MSSQL_PRODUCT_ID:-Developer}
    volumes:
      - vda_test_ms_sqlserver_data:/var/opt/mssql
      - ./db/init_db_logistics/init:/init
      - ./db/init_db_logistics/csv:/csv
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 5s
      timeout: 5s
      retries: 20

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Strong_password123!}
    volumes:
      - ./db/init_db_logistics/init:/init
      - ./db/init_db_logistics/csv:/csv
    entrypoint: ["/bin/bash", "-c"]
    command: > 
      "apt-get update && 
      apt-get install -y unixodbc && 
      /init/init.sh"

volumes:
  vda_test_ms_sqlserver_data:
