-- BikeStores Database Initialization Script (PostgreSQL)
-- =====================================================

-- Create Schemas
CREATE SCHEMA IF NOT EXISTS bike_stores;

-- PRODUCTION TABLES
-- =====================================================
CREATE TABLE categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL
);

CREATE TABLE brands (
    brand_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    brand_id INT NOT NULL,
    category_id INT NOT NULL,
    model_year SMALLINT NOT NULL,
    list_price DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (brand_id)
        REFERENCES brands(brand_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- SALES TABLES
-- =====================================================
CREATE TABLE stores (
    store_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name VARCHAR(255) NOT NULL,
    phone VARCHAR(25),
    email VARCHAR(255),
    street VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(10),
    zip_code VARCHAR(5)
);

CREATE TABLE staffs (
    staff_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(25),
    active SMALLINT NOT NULL,
    store_id INT NOT NULL,
    manager_id INT,
    FOREIGN KEY (store_id)
        REFERENCES stores(store_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (manager_id)
        REFERENCES staffs(staff_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE customers (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    street VARCHAR(255),
    city VARCHAR(50),
    state VARCHAR(25),
    zip_code VARCHAR(5)
);

CREATE TABLE orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT,
    order_status SMALLINT NOT NULL,
    order_date DATE NOT NULL,
    required_date DATE NOT NULL,
    shipped_date DATE,
    store_id INT NOT NULL,
    staff_id INT NOT NULL,
    FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (store_id)
        REFERENCES stores(store_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (staff_id)
        REFERENCES staffs(staff_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE order_items (
    order_id INT,
    item_id INT,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    list_price DECIMAL(10,2) NOT NULL,
    discount DECIMAL(4,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (order_id, item_id),
    FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE stocks (
    store_id INT,
    product_id INT,
    quantity INT,
    PRIMARY KEY (store_id, product_id),
    FOREIGN KEY (store_id)
        REFERENCES stores(store_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);


-- INDEXES FOR PERFORMANCE (JOINS + FILTERS)
-- =====================================================

-- products -> joins na brands, categories
CREATE INDEX idx_products_brand_id
    ON products(brand_id);

CREATE INDEX idx_products_category_id
    ON products(category_id);

-- stocks -> joins na stores, products
CREATE INDEX idx_stocks_store_id
    ON stocks(store_id);

CREATE INDEX idx_stocks_product_id
    ON stocks(product_id);

-- staffs -> join na stores + manager
CREATE INDEX idx_staffs_store_id
    ON staffs(store_id);

CREATE INDEX idx_staffs_manager_id
    ON staffs(manager_id);

-- orders -> veľmi časté joiny
CREATE INDEX idx_orders_customer_id
    ON orders(customer_id);

CREATE INDEX idx_orders_store_id
    ON orders(store_id);

CREATE INDEX idx_orders_staff_id
    ON orders(staff_id);

-- filtrovanie podľa dátumu
CREATE INDEX idx_orders_order_date
    ON orders(order_date);

-- order_items -> najdôležitejšia join tabuľka
CREATE INDEX idx_order_items_product_id
    ON order_items(product_id);

CREATE INDEX idx_order_items_order_id
    ON order_items(order_id);

-- customers (časté vyhľadávanie podľa emailu)
CREATE INDEX idx_customers_email
    ON customers(email);

-- COPY DATA FROM CSV FILES
-- =====================================================
COPY categories(category_id, category_name)
FROM '/docker-entrypoint-initdb.d/categories.csv'
DELIMITER ','
CSV HEADER;

COPY brands(brand_id, brand_name)
FROM '/docker-entrypoint-initdb.d/brands.csv'
DELIMITER ','
CSV HEADER;

COPY stores(store_id, store_name, phone, email, street, city, state, zip_code)
FROM '/docker-entrypoint-initdb.d/stores.csv'
DELIMITER ','
CSV HEADER;

COPY customers(customer_id, first_name, last_name, email, street, city, state, zip_code)
FROM '/docker-entrypoint-initdb.d/customers.csv'
DELIMITER ','
CSV HEADER;

COPY staffs(staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
FROM '/docker-entrypoint-initdb.d/staffs.csv'
DELIMITER ','
CSV HEADER
NULL 'NULL';

COPY products(product_id, product_name, brand_id, category_id, model_year, list_price)
FROM '/docker-entrypoint-initdb.d/products.csv'
DELIMITER ','
CSV HEADER;

COPY orders(order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id)
FROM '/docker-entrypoint-initdb.d/orders.csv'
DELIMITER ','
CSV HEADER;

COPY order_items(order_id, item_id, product_id, quantity, list_price, discount)
FROM '/docker-entrypoint-initdb.d/order_items.csv'
DELIMITER ','
CSV HEADER;

COPY stocks(store_id, product_id, quantity)
FROM '/docker-entrypoint-initdb.d/stocks.csv'
DELIMITER ','
CSV HEADER;

-- RESET SEQUENCES AFTER IMPORT
-- =====================================================
SELECT setval(pg_get_serial_sequence('categories', 'category_id'),
       (SELECT MAX(category_id) FROM categories));

SELECT setval(pg_get_serial_sequence('brands', 'brand_id'),
       (SELECT MAX(brand_id) FROM brands));

SELECT setval(pg_get_serial_sequence('products', 'product_id'),
       (SELECT MAX(product_id) FROM products));

SELECT setval(pg_get_serial_sequence('stores', 'store_id'),
       (SELECT MAX(store_id) FROM stores));

SELECT setval(pg_get_serial_sequence('staffs', 'staff_id'),
       (SELECT MAX(staff_id) FROM staffs));

SELECT setval(pg_get_serial_sequence('customers', 'customer_id'),
       (SELECT MAX(customer_id) FROM customers));

SELECT setval(pg_get_serial_sequence('orders', 'order_id'),
       (SELECT MAX(order_id) FROM orders));