ALTER TABLE loads
ADD CONSTRAINT FK_
FOREIGN KEY (_ID) REFERENCES Customers(_ID);

ALTER TABLE trips
ADD CONSTRAINT FK_
FOREIGN KEY (_ID) REFERENCES Customers(_ID);

ALTER TABLE fuel_purchases
ADD CONSTRAINT FK_
FOREIGN KEY (_ID) REFERENCES Customers(_ID);

ALTER TABLE maintenance_records
ADD CONSTRAINT FK_
FOREIGN KEY (_ID) REFERENCES Customers(_ID);

ALTER TABLE delivery_events
ADD CONSTRAINT FK_
FOREIGN KEY (_ID) REFERENCES Customers(_ID);

ALTER TABLE safety_incidents
ADD CONSTRAINT FK_
FOREIGN KEY (_ID) REFERENCES Customers(_ID);